//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentServiceRef
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Competency", Namespace = "http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Competency : object
    {

        private string CompetencyNameField;

        private string NationalCodeField;

        private string ResultsField;

        private string StudyPlanField;

        private string SubjectCodeField;

        private string SubjectNameField;

        private string TafeCodeField;

        private string TrainingPakckageUsageField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetencyName
        {
            get
            {
                return this.CompetencyNameField;
            }
            set
            {
                this.CompetencyNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyPlan
        {
            get
            {
                return this.StudyPlanField;
            }
            set
            {
                this.StudyPlanField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectCode
        {
            get
            {
                return this.SubjectCodeField;
            }
            set
            {
                this.SubjectCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TafeCode
        {
            get
            {
                return this.TafeCodeField;
            }
            set
            {
                this.TafeCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingPakckageUsage
        {
            get
            {
                return this.TrainingPakckageUsageField;
            }
            set
            {
                this.TrainingPakckageUsageField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Qualification", Namespace = "http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Qualification : object
    {

        private System.Collections.Generic.List<StudentServiceRef.Competency> CompetenciesField;

        private int CoreUnitsField;

        private int DoneCField;

        private int DoneEField;

        private int DoneLEField;

        private int DoneTotalField;

        private int ElectedUnitsField;

        private string NationalQualCodeField;

        private double ProgressField;

        private string QualCodeField;

        private string QualNameField;

        private int ReqListedElectedUnitsField;

        private string TafeQualCodeField;

        private int TotalUnitsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<StudentServiceRef.Competency> Competencies
        {
            get
            {
                return this.CompetenciesField;
            }
            set
            {
                this.CompetenciesField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoreUnits
        {
            get
            {
                return this.CoreUnitsField;
            }
            set
            {
                this.CoreUnitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneC
        {
            get
            {
                return this.DoneCField;
            }
            set
            {
                this.DoneCField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneE
        {
            get
            {
                return this.DoneEField;
            }
            set
            {
                this.DoneEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneLE
        {
            get
            {
                return this.DoneLEField;
            }
            set
            {
                this.DoneLEField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneTotal
        {
            get
            {
                return this.DoneTotalField;
            }
            set
            {
                this.DoneTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElectedUnits
        {
            get
            {
                return this.ElectedUnitsField;
            }
            set
            {
                this.ElectedUnitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalQualCode
        {
            get
            {
                return this.NationalQualCodeField;
            }
            set
            {
                this.NationalQualCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Progress
        {
            get
            {
                return this.ProgressField;
            }
            set
            {
                this.ProgressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualCode
        {
            get
            {
                return this.QualCodeField;
            }
            set
            {
                this.QualCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualName
        {
            get
            {
                return this.QualNameField;
            }
            set
            {
                this.QualNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReqListedElectedUnits
        {
            get
            {
                return this.ReqListedElectedUnitsField;
            }
            set
            {
                this.ReqListedElectedUnitsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TafeQualCode
        {
            get
            {
                return this.TafeQualCodeField;
            }
            set
            {
                this.TafeQualCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUnits
        {
            get
            {
                return this.TotalUnitsField;
            }
            set
            {
                this.TotalUnitsField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Student", Namespace = "http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Student : object
    {

        private string AddressField;

        private string DOBField;

        private string EmailField;

        private string FirstNameField;

        private string IdField;

        private string LastNameField;

        private string PasswordField;

        private string PhoneField;

        private System.Collections.Generic.List<StudentServiceRef.Qualification> QualificationsField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB
        {
            get
            {
                return this.DOBField;
            }
            set
            {
                this.DOBField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<StudentServiceRef.Qualification> Qualifications
        {
            get
            {
                return this.QualificationsField;
            }
            set
            {
                this.QualificationsField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "StudentServiceRef.IStudentService")]
    public interface IStudentService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetCompetencyList", ReplyAction = "http://tempuri.org/IStudentService/GetCompetencyListResponse")]
        System.Collections.Generic.List<StudentServiceRef.Competency> GetCompetencyList(string studentID, string qualificationID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetCompetencyList", ReplyAction = "http://tempuri.org/IStudentService/GetCompetencyListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Competency>> GetCompetencyListAsync(string studentID, string qualificationID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetQualificationList", ReplyAction = "http://tempuri.org/IStudentService/GetQualificationListResponse")]
        System.Collections.Generic.List<StudentServiceRef.Qualification> GetQualificationList(string studentID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetQualificationList", ReplyAction = "http://tempuri.org/IStudentService/GetQualificationListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Qualification>> GetQualificationListAsync(string studentID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetStudentById", ReplyAction = "http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        StudentServiceRef.Student GetStudentById(string studentId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetStudentById", ReplyAction = "http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<StudentServiceRef.Student> GetStudentByIdAsync(string studentId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/SelectQualification", ReplyAction = "http://tempuri.org/IStudentService/SelectQualificationResponse")]
        System.Collections.Generic.List<StudentServiceRef.Competency> SelectQualification(string qualificationID, string studentId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/SelectQualification", ReplyAction = "http://tempuri.org/IStudentService/SelectQualificationResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Competency>> SelectQualificationAsync(string qualificationID, string studentId);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/Login", ReplyAction = "http://tempuri.org/IStudentService/LoginResponse")]
        bool Login(string id, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/Login", ReplyAction = "http://tempuri.org/IStudentService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string id, string password);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/IsQualCompleted", ReplyAction = "http://tempuri.org/IStudentService/IsQualCompletedResponse")]
        bool IsQualCompleted(StudentServiceRef.Qualification sQual);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/IsQualCompleted", ReplyAction = "http://tempuri.org/IStudentService/IsQualCompletedResponse")]
        System.Threading.Tasks.Task<bool> IsQualCompletedAsync(StudentServiceRef.Qualification sQual);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IStudentServiceChannel : StudentServiceRef.IStudentService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<StudentServiceRef.IStudentService>, StudentServiceRef.IStudentService
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public StudentServiceClient(EndpointConfiguration endpointConfiguration) :
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), StudentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StudentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StudentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Collections.Generic.List<StudentServiceRef.Competency> GetCompetencyList(string studentID, string qualificationID)
        {
            return base.Channel.GetCompetencyList(studentID, qualificationID);
        }

        public System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Competency>> GetCompetencyListAsync(string studentID, string qualificationID)
        {
            return base.Channel.GetCompetencyListAsync(studentID, qualificationID);
        }

        public System.Collections.Generic.List<StudentServiceRef.Qualification> GetQualificationList(string studentID)
        {
            return base.Channel.GetQualificationList(studentID);
        }

        public System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Qualification>> GetQualificationListAsync(string studentID)
        {
            return base.Channel.GetQualificationListAsync(studentID);
        }

        public StudentServiceRef.Student GetStudentById(string studentId)
        {
            return base.Channel.GetStudentById(studentId);
        }

        public System.Threading.Tasks.Task<StudentServiceRef.Student> GetStudentByIdAsync(string studentId)
        {
            return base.Channel.GetStudentByIdAsync(studentId);
        }

        public System.Collections.Generic.List<StudentServiceRef.Competency> SelectQualification(string qualificationID, string studentId)
        {
            return base.Channel.SelectQualification(qualificationID, studentId);
        }

        public System.Threading.Tasks.Task<System.Collections.Generic.List<StudentServiceRef.Competency>> SelectQualificationAsync(string qualificationID, string studentId)
        {
            return base.Channel.SelectQualificationAsync(qualificationID, studentId);
        }

        public bool Login(string id, string password)
        {
            return base.Channel.Login(id, password);
        }

        public System.Threading.Tasks.Task<bool> LoginAsync(string id, string password)
        {
            return base.Channel.LoginAsync(id, password);
        }

        public bool IsQualCompleted(StudentServiceRef.Qualification sQual)
        {
            return base.Channel.IsQualCompleted(sQual);
        }

        public System.Threading.Tasks.Task<bool> IsQualCompletedAsync(StudentServiceRef.Qualification sQual)
        {
            return base.Channel.IsQualCompletedAsync(sQual);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IStudentService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentService))
            {
                return new System.ServiceModel.EndpointAddress("http://srvwcfservice.azurewebsites.net/services/StudentService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IStudentService))
            {
                return new System.ServiceModel.EndpointAddress("https://srvwcfservice.azurewebsites.net/services/StudentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IStudentService,

            BasicHttpsBinding_IStudentService,
        }
    }
}
