//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Student : object
    {
        
        private string EmailAddressField;
        
        private string GivenNameField;
        
        private string LastNameField;
        
        private StudentServiceRef.Qualification QualificationField;
        
        private string StudentIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GivenName
        {
            get
            {
                return this.GivenNameField;
            }
            set
            {
                this.GivenNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentServiceRef.Qualification Qualification
        {
            get
            {
                return this.QualificationField;
            }
            set
            {
                this.QualificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentID
        {
            get
            {
                return this.StudentIDField;
            }
            set
            {
                this.StudentIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Qualification", Namespace="http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Qualification : object
    {
        
        private StudentServiceRef.Competency[] CompetenciesField;
        
        private int CoreUnitsField;
        
        private int DoneCField;
        
        private int DoneEField;
        
        private int DoneLEField;
        
        private int DoneTotalField;
        
        private int ElectedUnitsField;
        
        private string NationalQualCodeField;
        
        private string QualCodeField;
        
        private string QualNameField;
        
        private int ReqListedElectedUnitsField;
        
        private string TafeQualCodeField;
        
        private int TotalUnitsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentServiceRef.Competency[] Competencies
        {
            get
            {
                return this.CompetenciesField;
            }
            set
            {
                this.CompetenciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CoreUnits
        {
            get
            {
                return this.CoreUnitsField;
            }
            set
            {
                this.CoreUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneC
        {
            get
            {
                return this.DoneCField;
            }
            set
            {
                this.DoneCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneE
        {
            get
            {
                return this.DoneEField;
            }
            set
            {
                this.DoneEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneLE
        {
            get
            {
                return this.DoneLEField;
            }
            set
            {
                this.DoneLEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DoneTotal
        {
            get
            {
                return this.DoneTotalField;
            }
            set
            {
                this.DoneTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ElectedUnits
        {
            get
            {
                return this.ElectedUnitsField;
            }
            set
            {
                this.ElectedUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalQualCode
        {
            get
            {
                return this.NationalQualCodeField;
            }
            set
            {
                this.NationalQualCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualCode
        {
            get
            {
                return this.QualCodeField;
            }
            set
            {
                this.QualCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualName
        {
            get
            {
                return this.QualNameField;
            }
            set
            {
                this.QualNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReqListedElectedUnits
        {
            get
            {
                return this.ReqListedElectedUnitsField;
            }
            set
            {
                this.ReqListedElectedUnitsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TafeQualCode
        {
            get
            {
                return this.TafeQualCodeField;
            }
            set
            {
                this.TafeQualCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalUnits
        {
            get
            {
                return this.TotalUnitsField;
            }
            set
            {
                this.TotalUnitsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Competency", Namespace="http://schemas.datacontract.org/2004/07/SRV_WcfService")]
    public partial class Competency : object
    {
        
        private StudentServiceRef.Competency[] CompetenciesField;
        
        private string CompetencyNameField;
        
        private string NationalCodeField;
        
        private string ResultsField;
        
        private string StudyPlanField;
        
        private string SubjectCodeField;
        
        private string SubjectNameField;
        
        private string TafeCodeField;
        
        private string TrainingPakckageUsageField;
        
        private StudentServiceRef.Competency[] competenciesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentServiceRef.Competency[] Competencies
        {
            get
            {
                return this.CompetenciesField;
            }
            set
            {
                this.CompetenciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompetencyName
        {
            get
            {
                return this.CompetencyNameField;
            }
            set
            {
                this.CompetencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalCode
        {
            get
            {
                return this.NationalCodeField;
            }
            set
            {
                this.NationalCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudyPlan
        {
            get
            {
                return this.StudyPlanField;
            }
            set
            {
                this.StudyPlanField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectCode
        {
            get
            {
                return this.SubjectCodeField;
            }
            set
            {
                this.SubjectCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectName
        {
            get
            {
                return this.SubjectNameField;
            }
            set
            {
                this.SubjectNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TafeCode
        {
            get
            {
                return this.TafeCodeField;
            }
            set
            {
                this.TafeCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingPakckageUsage
        {
            get
            {
                return this.TrainingPakckageUsageField;
            }
            set
            {
                this.TrainingPakckageUsageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StudentServiceRef.Competency[] competencies
        {
            get
            {
                return this.competenciesField;
            }
            set
            {
                this.competenciesField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceRef.IStudentService")]
    public interface IStudentService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentById", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        StudentServiceRef.Student GetStudentById(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentById", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIdResponse")]
        System.Threading.Tasks.Task<StudentServiceRef.Student> GetStudentByIdAsync(string studentId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        bool Login(string inUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/Login", ReplyAction="http://tempuri.org/IStudentService/LoginResponse")]
        System.Threading.Tasks.Task<bool> LoginAsync(string inUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CalQualProgress", ReplyAction="http://tempuri.org/IStudentService/CalQualProgressResponse")]
        double CalQualProgress(string studentID, string qualCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CalQualProgress", ReplyAction="http://tempuri.org/IStudentService/CalQualProgressResponse")]
        System.Threading.Tasks.Task<double> CalQualProgressAsync(string studentID, string qualCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetQualificationList", ReplyAction="http://tempuri.org/IStudentService/GetQualificationListResponse")]
        StudentServiceRef.Qualification[] GetQualificationList(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetQualificationList", ReplyAction="http://tempuri.org/IStudentService/GetQualificationListResponse")]
        System.Threading.Tasks.Task<StudentServiceRef.Qualification[]> GetQualificationListAsync(string studentID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetCompetencyList", ReplyAction="http://tempuri.org/IStudentService/GetCompetencyListResponse")]
        StudentServiceRef.Competency[] GetCompetencyList(string studentID, string qualificationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetCompetencyList", ReplyAction="http://tempuri.org/IStudentService/GetCompetencyListResponse")]
        System.Threading.Tasks.Task<StudentServiceRef.Competency[]> GetCompetencyListAsync(string studentID, string qualificationID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetQualification", ReplyAction="http://tempuri.org/IStudentService/GetQualificationResponse")]
        StudentServiceRef.Qualification GetQualification(string qualCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetQualification", ReplyAction="http://tempuri.org/IStudentService/GetQualificationResponse")]
        System.Threading.Tasks.Task<StudentServiceRef.Qualification> GetQualificationAsync(string qualCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public interface IStudentServiceChannel : StudentServiceRef.IStudentService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<StudentServiceRef.IStudentService>, StudentServiceRef.IStudentService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public StudentServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), StudentServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(StudentServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public StudentServiceRef.Student GetStudentById(string studentId)
        {
            return base.Channel.GetStudentById(studentId);
        }
        
        public System.Threading.Tasks.Task<StudentServiceRef.Student> GetStudentByIdAsync(string studentId)
        {
            return base.Channel.GetStudentByIdAsync(studentId);
        }
        
        public bool Login(string inUserId)
        {
            return base.Channel.Login(inUserId);
        }
        
        public System.Threading.Tasks.Task<bool> LoginAsync(string inUserId)
        {
            return base.Channel.LoginAsync(inUserId);
        }
        
        public double CalQualProgress(string studentID, string qualCode)
        {
            return base.Channel.CalQualProgress(studentID, qualCode);
        }
        
        public System.Threading.Tasks.Task<double> CalQualProgressAsync(string studentID, string qualCode)
        {
            return base.Channel.CalQualProgressAsync(studentID, qualCode);
        }
        
        public StudentServiceRef.Qualification[] GetQualificationList(string studentID)
        {
            return base.Channel.GetQualificationList(studentID);
        }
        
        public System.Threading.Tasks.Task<StudentServiceRef.Qualification[]> GetQualificationListAsync(string studentID)
        {
            return base.Channel.GetQualificationListAsync(studentID);
        }
        
        public StudentServiceRef.Competency[] GetCompetencyList(string studentID, string qualificationID)
        {
            return base.Channel.GetCompetencyList(studentID, qualificationID);
        }
        
        public System.Threading.Tasks.Task<StudentServiceRef.Competency[]> GetCompetencyListAsync(string studentID, string qualificationID)
        {
            return base.Channel.GetCompetencyListAsync(studentID, qualificationID);
        }
        
        public StudentServiceRef.Qualification GetQualification(string qualCode)
        {
            return base.Channel.GetQualification(qualCode);
        }
        
        public System.Threading.Tasks.Task<StudentServiceRef.Qualification> GetQualificationAsync(string qualCode)
        {
            return base.Channel.GetQualificationAsync(qualCode);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IStudentService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IStudentService))
            {
                return new System.ServiceModel.EndpointAddress("http://srvwcfservice.azurewebsites.net/services/StudentService.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_IStudentService))
            {
                return new System.ServiceModel.EndpointAddress("https://srvwcfservice.azurewebsites.net/services/StudentService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IStudentService,
            
            BasicHttpsBinding_IStudentService,
        }
    }
}
